title: Selena Slaughter's Portfolio
logo: cocoacoder95/SSlaughterPortfolio.github.io/ProfileImageTemp.png
description: "Below are examples of projects I have done" 
show_downloads: true
theme: jekyll-theme-merlot
