title: Selena Slaughter's Portfolio
#logo:
description: Hello I am currently an IT specalist with a passion for Data Analytics. I have experience with BASH and Linux scripting, SQL, Python and C++. 
Below are some examples of personal projects I have completed. 
show_downloads: true
theme: jekyll-theme-merlot
